# Generated by `inincompatibility`.
# **Not** depend on `incompatibility`. :)
# Please use this file to `import`.
import socket
import pickle

BUFFER_SIZE = 4096

client = socket.socket(2, socket.SOCK_STREAM)
client.connect(('127.0.0.1', 35919))


def _func_eval(func, args, kwargs):
    data = pickle.dumps((func, args, kwargs))
    client.sendall(data)
    return pickle.loads(client.recv(BUFFER_SIZE))


def _inincompatibility_remote_eval(*args, **kwargs):
    return _func_eval('_inincompatibility_remote_eval', args, kwargs)


def _inincompatibility_remote_exec(*args, **kwargs):
    return _func_eval('_inincompatibility_remote_exec', args, kwargs)


def getdata(*args, **kwargs):
    return _func_eval('getdata', args, kwargs)


def calc(*args, **kwargs):
    return _func_eval('calc', args, kwargs)
